
name: Basic CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "GitHub Actions is working!"

      - name: Display Student Name
        run: echo "Hello Mohamed Shahid!"

      - name: Run Tests
        run: echo "All tests completed successfully!"
